### ISSUE TITLE
SingleCellDataBinatization error?

### ISSUE THREAD

**Issue by lb15** [morris-lab/CellTagR#3]
Hi CellTag team,

I've run through the CellTagR tutorial with my data and created a bam.test.obj with the v1 and v3 celltag libraries (I did not transduce the v2 library). I've been using the starcode colIapsing of celltags. I noticed after running the v3 library that I was getting this output after running SingleCellDataBinatization:

`[1] "Binarized"
Average:  NA 
Frequency:  NA `

for the v1 library it looked like this:
`[1] "Binarized"
Average:  14.61329 
Frequency:  19.40946 `

I was able to continue forward and running the Jaccard analysis and call clones. I noticed when comparing my object to your provided V1V2V3 object, that the binary.mtx slot looks different, specifically the @p slot, where I think it should be 0 and 1s for the matrix. I have numbers > 1. 

str(v1v2v3 object from tutorial)
`..@ binary.mtx           :Formal class 'dgCMatrix' [package "Matrix"] with 6 slots
  .. .. ..@ i       : int [1:21330] 1444 1181 3221 1274 1145 9 36 225 295 368 ...
  .. .. ..@ p       : int [1:19196] 0 0 0 0 0 1 1 1 1 1 ...
  .. .. ..@ Dim     : int [1:2] 3812 19195
  .. .. ..@ Dimnames:List of 2
  .. .. .. ..$ : chr [1:3812] "AAACCTGAGTATGACA-1" "AAACCTGCAGCCTATA-1" "AAACCTGGTAAGTAGT-1" "AAACCTGTCACAACGT-1" ...
  .. .. .. ..$ : chr [1:19195] "v1.AAAAAAGA" "v1.AAAAAAGC" "v1.AAAAAATA" "v1.AAAAACTC" ...
  .. .. ..@ x       : num [1:21330] 1 1 1 1 1 1 1 1 1 1 ...
  .. .. ..@ factors : list()`

str(my_object)
` ..@ binary.mtx           :Formal class 'dgCMatrix' [package "Matrix"] with 6 slots
  .. .. ..@ i       : int [1:2991588] 3040 242 1165 3051 4110 4333 4736 4814 4971 7886 ...
  .. .. ..@ p       : int [1:32203] 0 1 1 21 22 22 23 24 79 80 ...
  .. .. ..@ Dim     : int [1:2] 18652 32202
  .. .. ..@ Dimnames:List of 2
  .. .. .. ..$ : chr [1:18652] "AAACCCAAGACTACCT-1" "AAACCCAAGACTTGTC-1" "AAACCCAAGCGGGTTA-1" "AAACCCAAGGTTAGTA-1" ...
  .. .. .. ..$ : chr [1:32202] "v1.v1.AAAAAAAA" "v1.v1.AAAAAAAC" "v1.v1.AAAAAAGA" "v1.v1.AAAAAAGC" ...
  .. .. ..@ x       : num [1:2991588] 1 1 1 1 1 1 1 1 1 1 ...
  .. .. ..@ factors : list()`

I'm not sure what to think of this, if I should be concerned or it means something went wrong in my collapsing? I'm currently running now without any starcode collapsing to see if I get the same thing.

Thanks for any advice!

Sincerely,
Lauren

**Comment by babiddy** [comment]
Hi Lauren,

I am not exactly sure what the issue is but having numbers other than 1s and 0s in the @p slot is expected. Because this is a sparse matrix the @p slot does not actually contain the matrix values. The values are kept in the @x slot. So the @x slot should contain only 1s and 0s. It would be helpful if you could check those values by running a command like `table(my_object@x)` and see if there are any NAs or values other than 1 or 0. 

Also, it looks like the column (or CellTag) names for your matrix have multiple `v1.` prefixes. This could cause issues and might be the source of the error. I would try re-running the SingleCellBinarization command and ensure that these names are consistent.

I hope this helps.

Best,
Brent

**Comment by lb15** [comment]
Hi Brent,
I reran the pipeline from the start and it fixed the NAs in the binarized output. Perhaps something got run twice and didn't overwrite properly. Thanks for your explanations on cell object and your help!
