### ISSUE TITLE
statistical analysis to detect fate bias in clones

### ISSUE THREAD

**Issue by lb15** [morris-lab/CellTagR#9]
Hi Morris Lab!

I've run the CellTagR pipeline on my test dataset. I'd now like to do some statistical analyses and power calculations to look for lineage fate bias in my clones and the required cell number to robustly detect biases. 

In your Nature paper there is a description of comparing trajectories in the paragraph "Trajectory discovery via randomized testing." Would you be able to share the R script used to run this analysis? 

Did you perform power analysis to determine the minimum number of cells needed to compare clonal fates? I have a case where I have relatively small clone sizes (2-8 cells), so I am trying to determine how I can ensure enough statistical power to identify clonal bias. With smaller clones sizes, I am sure I will need higher numbers of total cells, but I need to figure out how much higher.

Thanks for any advice!

Sincerely,
Lauren

**Comment by KaetheKong** [comment]
Hi Lauren,

Glad to hear the CellTagR pipeline runs successfully for you!

Yes! I will share the code as a part of the Examples folder. We had python and R scripts for this randomized test. Please feel free to use either one of them. The general hypothesis that we were testing in the paper is to test if a clone contains a higher/lower percentage of cells falling into the reprogrammed/dead-end clusters. The clusters are defined based on marker expression annotation and Seurat clustering analysis. The current scripts could be a little messy. Please let us know if you have further questions.

Regarding the power analysis, we didn't perform a power analysis because we assume the distributions to compare via randomized testing is non-parametric. And the reason why we selected 35 cells to be the minimum baseline for this test is that since we are comparing composition percentages, having fewer cells will make the distribution discrete, which we would instead want it to be continuous. And I think power analysis requires prior information regarding the distribution and effect size (like how big/small a difference are you expecting).

For estimation of the total number of cells to get a targeted clone size, we suggest using the CellTag simulator on [CellTag Viz](http://celltag.org/) to provide some insights about cell number.

Hope this helps!
Best,
Wenjun
